import React from 'react';
import type { FinishResults } from '../../../core/finishCalculations';

interface Props {
  results: FinishResults;
  }

  const cardStyle: React.CSSProperties = {
    background: '#fff',
      border: '1px solid #ddd',
        borderRadius: 12,
          overflow: 'hidden',
            marginBottom: 12,
            };

            const headStyle: React.CSSProperties = {
              background: '#f8fafc',
                padding: '10px 12px',
                  fontWeight: 700,
                    color: '#003366',
                      fontSize: 14,
                        borderBottom: '1px solid #ddd',
                        };

                        const bodyStyle: React.CSSProperties = {
                          padding: 10,
                          };

                          const tableStyle: React.CSSProperties = {
                            width: '100%',
                              borderCollapse: 'collapse',
                                fontSize: 12,
                                };

                                const thStyle: React.CSSProperties = {
                                  background: '#003366',
                                    color: 'white',
                                      padding: '8px 6px',
                                        border: '1px solid #003366',
                                          textAlign: 'center',
                                          };

                                          const tdStyle: React.CSSProperties = {
                                            padding: '7px 6px',
                                              border: '1px solid #ccc',
                                                textAlign: 'center',
                                                };

                                                export const OpeningTables: React.FC<Props> = ({ results }) => {
                                                  return (
                                                      <>
                                                            {/* جدول النوافذ */}
                                                                  <div style={cardStyle}>
                                                                          <div style={headStyle}>🪟 بند النوافذ</div>
                                                                                  <div style={bodyStyle}>
                                                                                            <table style={tableStyle}>
                                                                                                        <thead>
                                                                                                                      <tr>
                                                                                                                                      <th style={thStyle}>عدد النوافذ</th>
                                                                                                                                                      <th style={thStyle}>الأبعاد (م)</th>
                                                                                                                                                                      <th style={thStyle}>مساحة النافذة (م²)</th>
                                                                                                                                                                                      <th style={thStyle}>إجمالي المساحات (م²)</th>
                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                </thead>
                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                          {results.windowGroups.map((g, i) => (
                                                                                                                                                                                                                                                          <tr key={i}>
                                                                                                                                                                                                                                                                            <td style={tdStyle}>{g.count}</td>
                                                                                                                                                                                                                                                                                              <td style={tdStyle}>{g.width} × {g.height}</td>
                                                                                                                                                                                                                                                                                                                <td style={tdStyle}>{g.unitArea.toFixed(2)}</td>
                                                                                                                                                                                                                                                                                                                                  <td style={tdStyle}>{g.totalArea.toFixed(2)}</td>
                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                              <tr style={{ background: '#f0f0f0', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                              <td style={tdStyle} colSpan={3}>إجمالي مساحات النوافذ</td>
                                                                                                                                                                                                                                                                                                                                                                                                              <td style={tdStyle}>{results.windowGroups.reduce((s, g) => s + g.totalArea, 0).toFixed(2)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* جدول الأبواب */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={headStyle}>🚪 بند الأبواب</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={bodyStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <table style={tableStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th style={thStyle}>عدد الأبواب</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th style={thStyle}>الأبعاد (م)</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th style={thStyle}>مساحة الباب (م²)</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th style={thStyle}>إجمالي المساحات (م²)</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {results.doorGroups.map((g, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr key={i}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td style={tdStyle}>{g.count}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td style={tdStyle}>{g.width} × {g.height}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style={tdStyle}>{g.unitArea.toFixed(2)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td style={tdStyle}>{g.totalArea.toFixed(2)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr style={{ background: '#f0f0f0', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td style={tdStyle} colSpan={3}>إجمالي مساحات الأبواب</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td style={tdStyle}>{results.doorGroups.reduce((s, g) => s + g.totalArea, 0).toFixed(2)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };