import React, { useState } from 'react';
import { calculateFinishes, type FinishesInput, type FinishResults } from '../../core/finishCalculations';
import type { Wall, Column, Window, Door } from '../../core/types';
import type { RoomRegion } from '../../core/regionTypes';
import { FinishInputs } from './FinishInputs';
import { FinishTables } from './FinishTables';

interface Props {
  walls: Wall[];
    columns: Column[];
      windows: Window[];
        doors: Door[];
          regions: RoomRegion[];
          }

          export const FinishesPage: React.FC<Props> = ({ walls, columns, windows, doors, regions }) => {
            const [floorHeight, setFloorHeight] = useState(3);
              const [hasMarble, setHasMarble] = useState<boolean>(false);
                const [results, setResults] = useState<FinishResults | null>(null);
                  const [electricalPts, setElectricalPts] = useState(0);
                    const [plumbingPts, setPlumbingPts] = useState(0);

                      const calculate = () => {
                          const input: FinishesInput = { floorHeight, hasMarble };
                              const res = calculateFinishes(walls, columns, windows, doors, regions, input);

                                  const roundedRes = { ...res };
                                      roundedRes.exteriorBlocks = Math.ceil(res.exteriorBlocks);
                                          roundedRes.interiorBlocks = Math.ceil(res.interiorBlocks);
                                              roundedRes.exteriorBlockCement = Math.ceil(res.exteriorBlockCement);
                                                  roundedRes.interiorBlockCement = Math.ceil(res.interiorBlockCement);
                                                      roundedRes.exteriorBlockSand = Math.ceil(res.exteriorBlockSand);
                                                          roundedRes.interiorBlockSand = Math.ceil(res.interiorBlockSand);
                                                              roundedRes.plasterWallsLabor = Math.ceil(res.plasterWallsLabor);
                                                                  roundedRes.plasterCeilingLabor = Math.ceil(res.plasterCeilingLabor);
                                                                      roundedRes.plasterWallsMaterial = Math.ceil(res.plasterWallsMaterial);
                                                                          roundedRes.plasterCement = Math.ceil(res.plasterCement);
                                                                              roundedRes.plasterSand = Math.ceil(res.plasterSand);
                                                                                  roundedRes.paintWalls = Math.ceil(res.paintWalls);
                                                                                      roundedRes.paintCeiling = Math.ceil(res.paintCeiling);
                                                                                          roundedRes.putty = Math.ceil(res.putty);
                                                                                              roundedRes.primer = Math.ceil(res.primer);
                                                                                                  roundedRes.paint = Math.ceil(res.paint);
                                                                                                      roundedRes.tileFloorArea = Math.ceil(res.tileFloorArea);
                                                                                                          roundedRes.tileKitchenFloor = Math.ceil(res.tileKitchenFloor);
                                                                                                              roundedRes.tileBathroomFloor = Math.ceil(res.tileBathroomFloor);
                                                                                                                  roundedRes.tileKitchenWalls = Math.ceil(res.tileKitchenWalls);
                                                                                                                      roundedRes.tileBathroomWalls = Math.ceil(res.tileBathroomWalls);
                                                                                                                          roundedRes.tileCement = Math.ceil(res.tileCement);
                                                                                                                              roundedRes.tileSand = Math.ceil(res.tileSand);
                                                                                                                                  roundedRes.marbleArea = Math.ceil(res.marbleArea);
                                                                                                                                      roundedRes.marbleConcrete = Math.ceil(res.marbleConcrete);
                                                                                                                                          roundedRes.marbleCement = Math.ceil(res.marbleCement);
                                                                                                                                              roundedRes.marbleSand = Math.ceil(res.marbleSand);
                                                                                                                                                  roundedRes.marbleAggregate = Math.ceil(res.marbleAggregate);
                                                                                                                                                      roundedRes.electricalPoints = Math.ceil(res.electricalPoints);
                                                                                                                                                          roundedRes.plumbingPoints = Math.ceil(res.plumbingPoints);
                                                                                                                                                              roundedRes.windowGroups = res.windowGroups;
                                                                                                                                                                  roundedRes.doorGroups = res.doorGroups;

                                                                                                                                                                      setResults(roundedRes);
                                                                                                                                                                          setElectricalPts(Math.ceil(res.electricalPoints));
                                                                                                                                                                              setPlumbingPts(Math.ceil(res.plumbingPoints));

                                                                                                                                                                                  // ✅ حساب الإجماليات النهائية (مطابقة لجدول إجمالي الكميات النهائي في صفحة التشطيبات)
                                                                                                                                                                                      const totalBlocks = Math.ceil(roundedRes.exteriorBlocks + roundedRes.interiorBlocks);
                                                                                                                                                                                          
                                                                                                                                                                                              const correctedPlasterWalls = Math.max(0, roundedRes.plasterWallsLabor - (roundedRes.intWindowArea + roundedRes.intDoorArea + roundedRes.extWindowArea + roundedRes.extDoorArea) - (roundedRes.tileKitchenWalls + roundedRes.tileBathroomWalls));
                                                                                                                                                                                                  const correctedPlasterCeiling = Math.max(0, roundedRes.plasterCeilingLabor - roundedRes.innerWallArea);
                                                                                                                                                                                                      const correctedPlasterArea = correctedPlasterWalls + correctedPlasterCeiling;
                                                                                                                                                                                                          const correctedPlasterCement = Math.ceil(correctedPlasterArea * 0.15);
                                                                                                                                                                                                              const correctedPlasterSand = Math.ceil(correctedPlasterCement * 0.15);

                                                                                                                                                                                                                  const correctedTileFloor = Math.max(0, roundedRes.tileFloorArea - roundedRes.innerWallArea);
                                                                                                                                                                                                                      const correctedTileKitchenWalls = Math.max(0, roundedRes.tileKitchenWalls - 2);
                                                                                                                                                                                                                          const correctedTileBathroomWalls = Math.max(0, roundedRes.tileBathroomWalls - 2);
                                                                                                                                                                                                                              const correctedTileTotalArea = correctedTileFloor + roundedRes.tileKitchenFloor + roundedRes.tileBathroomFloor + correctedTileKitchenWalls + correctedTileBathroomWalls;
                                                                                                                                                                                                                                  const correctedTileCement = Math.ceil(correctedTileTotalArea * 0.3);
                                                                                                                                                                                                                                      const correctedTileSand = Math.ceil(correctedTileCement * 0.15);

                                                                                                                                                                                                                                          const marbleArea = hasMarble ? Math.max(0, roundedRes.exteriorWallGross - roundedRes.extWindowArea - roundedRes.extDoorArea) : 0;
                                                                                                                                                                                                                                              const marbleCement = hasMarble ? Math.ceil(marbleArea * 0.3) : 0;
                                                                                                                                                                                                                                                  const marbleSand = hasMarble ? Math.ceil(marbleCement * 0.07) : 0;
                                                                                                                                                                                                                                                      const marbleAggregate = hasMarble ? Math.ceil(marbleCement * 0.075) : 0;

                                                                                                                                                                                                                                                          const totalCement = Math.ceil(roundedRes.exteriorBlockCement + roundedRes.interiorBlockCement + correctedPlasterCement + correctedTileCement + marbleCement);
                                                                                                                                                                                                                                                              const totalSand = Math.ceil(roundedRes.exteriorBlockSand + roundedRes.interiorBlockSand + correctedPlasterSand + correctedTileSand + marbleSand);
                                                                                                                                                                                                                                                                  const totalAggregate = marbleAggregate;
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                          const totalDoors = roundedRes.doorGroups.reduce((s, g) => s + g.count, 0);
                                                                                                                                                                                                                                                                              const totalWindows = roundedRes.windowGroups.reduce((s, g) => s + g.count, 0);

                                                                                                                                                                                                                                                                                  // حفظ جميع البيانات في localStorage
                                                                                                                                                                                                                                                                                      const dataToSave = {
                                                                                                                                                                                                                                                                                            // الإجماليات
                                                                                                                                                                                                                                                                                                  totalBlocks,
                                                                                                                                                                                                                                                                                                        totalCement,
                                                                                                                                                                                                                                                                                                              totalSand,
                                                                                                                                                                                                                                                                                                                    totalAggregate,
                                                                                                                                                                                                                                                                                                                          totalMarbleArea: marbleArea,
                                                                                                                                                                                                                                                                                                                                totalDoors,
                                                                                                                                                                                                                                                                                                                                      totalWindows,
                                                                                                                                                                                                                                                                                                                                            // البلوك
                                                                                                                                                                                                                                                                                                                                                  blockOuter: { blocks: roundedRes.exteriorBlocks, cement: roundedRes.exteriorBlockCement, sand: roundedRes.exteriorBlockSand },
                                                                                                                                                                                                                                                                                                                                                        blockInner: { blocks: roundedRes.interiorBlocks, cement: roundedRes.interiorBlockCement, sand: roundedRes.interiorBlockSand },
                                                                                                                                                                                                                                                                                                                                                              // التلييس
                                                                                                                                                                                                                                                                                                                                                                    plaster: { area: roundedRes.plasterWallsLabor, cement: roundedRes.plasterCement, sand: roundedRes.plasterSand },
                                                                                                                                                                                                                                                                                                                                                                          // الطلاء
                                                                                                                                                                                                                                                                                                                                                                                paint: { area: roundedRes.paintWalls, putty: roundedRes.putty, primer: roundedRes.primer, paint: roundedRes.paint },
                                                                                                                                                                                                                                                                                                                                                                                      // البلاط
                                                                                                                                                                                                                                                                                                                                                                                            tile: { floor: roundedRes.tileFloorArea, kitchenWalls: roundedRes.tileKitchenWalls, bathroomWalls: roundedRes.tileBathroomWalls },
                                                                                                                                                                                                                                                                                                                                                                                                  // الرخام
                                                                                                                                                                                                                                                                                                                                                                                                        marble: { area: roundedRes.marbleArea, aggregate: roundedRes.marbleAggregate, cement: roundedRes.marbleCement, sand: roundedRes.marbleSand },
                                                                                                                                                                                                                                                                                                                                                                                                              // الإضافات
                                                                                                                                                                                                                                                                                                                                                                                                                    extras: { bathrooms: regions.filter(r => r.type === 'bathroom').length, kitchens: regions.filter(r => r.type === 'kitchen').length, windows: windows.length, doors: doors.length },
                                                                                                                                                                                                                                                                                                                                                                                                                          // عمالة
                                                                                                                                                                                                                                                                                                                                                                                                                                labor: { blockArea: roundedRes.exteriorWallNet + roundedRes.interiorWallNet },
                                                                                                                                                                                                                                                                                                                                                                                                                                      // مساحات إضافية
                                                                                                                                                                                                                                                                                                                                                                                                                                            exteriorWallNet: roundedRes.exteriorWallNet,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  interiorWallNet: roundedRes.interiorWallNet,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        exteriorWallGross: roundedRes.exteriorWallGross,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              interiorWallGross: roundedRes.interiorWallGross,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    paintWalls: roundedRes.paintWalls,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          paintCeiling: roundedRes.paintCeiling,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                plasterWallsLabor: roundedRes.plasterWallsLabor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      plasterCeilingLabor: roundedRes.plasterCeilingLabor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            innerWallArea: roundedRes.innerWallArea,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tileFloorArea: roundedRes.tileFloorArea,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tileKitchenFloor: roundedRes.tileKitchenFloor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tileBathroomFloor: roundedRes.tileBathroomFloor,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tileKitchenWalls: roundedRes.tileKitchenWalls,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tileBathroomWalls: roundedRes.tileBathroomWalls,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                         localStorage.setItem('hasMarble', JSON.stringify(hasMarble));                                                                                                                                                                                                                                                                                                                                                                                                                         localStorage.setItem('finishes_results', JSON.stringify(dataToSave));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ padding: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <FinishInputs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        floorHeight={floorHeight}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hasMarble={hasMarble}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onFloorHeightChange={setFloorHeight}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onHasMarbleChange={setHasMarble}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onCalculate={calculate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {results && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <FinishTables
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      results={results}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hasMarble={hasMarble}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          electricalPts={electricalPts}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    plumbingPts={plumbingPts}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onElectricalChange={setElectricalPts}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPlumbingChange={setPlumbingPts}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };