import React from 'react';
import { Card, Tr, Tr4, S } from './summaryComponents';

const n = (v: any) => { const num = parseFloat(v); return isNaN(num) ? 0 : num; };
const fmt = (v: number) => v.toFixed(2).replace(/\.00$/, '');
const fm = (v: number) => v.toLocaleString('en-US', { maximumFractionDigits: 0 });

export const SummaryTables2 = ({ data, o, setO, cur, cv, floors, hasMarble = false }: any) => {
  const { finishes = {}, prices = {}, struct = {}, prelim = {}, buildingArea = 0 } = data;
    const fmat = prices.finishesMaterials || [];
      const flab = prices.finishesLabor || [];
        const fext = prices.finishesExtra || [];
          const doorsAndWindows = prices.doorsAndWindows || [];

            // ✅ قراءة الإجماليات من finishes (من جداول التشطيبات)
              const totalBlocks = Math.ceil(n(finishes?.totalBlocks) * floors);
                const totalCement = Math.ceil(n(finishes?.totalCement) * floors);
                  const totalSand = Math.ceil(n(finishes?.totalSand) * floors);
                    const totalAggregate = Math.ceil(n(finishes?.totalAggregate) * floors);
                      const totalMarbleArea = Math.ceil(n(finishes?.totalMarbleArea) * floors);
                        const totalDoors = Math.ceil(n(finishes?.totalDoors) * floors);
                          const totalWindows = Math.ceil(n(finishes?.totalWindows) * floors);

                            // ✅ قراءة عمالة التشطيبات من جدول إجمالي كميات العمالة
                              const totalWallLaborFloors = Math.ceil((n(finishes?.exteriorWallGross) + n(finishes?.interiorWallGross)) * floors);
                                const totalPlasterLaborFloors = Math.ceil((n(finishes?.plasterWallsLabor) + (n(finishes?.plasterCeilingLabor) - n(finishes?.innerWallArea))) * floors);
                                  const totalPaintLaborFloors = Math.ceil((n(finishes?.paintWalls) + (n(finishes?.paintCeiling) - n(finishes?.innerWallArea))) * floors);
                                    const totalTileLaborFloors = Math.ceil(((n(finishes?.tileFloorArea) - n(finishes?.innerWallArea)) + n(finishes?.tileKitchenFloor) + n(finishes?.tileBathroomFloor) + n(finishes?.tileKitchenWalls) + n(finishes?.tileBathroomWalls)) * floors);

                                      // ✅ عمالة الرخام: من جدول بند كميات العمالة (بدون خصم) مضروبة في عدد الأدوار
                                        const totalMarbleLaborFloors = hasMarble ? Math.ceil(n(finishes?.exteriorWallGross) * floors) : 0;

                                          // ✅ عمالة بناء البلوك = نفس قيمة عمالة الجدران (totalWallLaborFloors)
                                            const blockLaborArea = totalWallLaborFloors;

                                              // إعدادات عمالة البلوك
                                                const blockLaborMode = prices.blockMode || 'm2';
                                                  const blockLaborUnit = n(flab[0]?.price || '0');

                                                    const totalSteelCost = n(struct?.totalSteel) * n(prices.steelUnified || '0');
                                                      const totalConcreteCost = n(struct?.totalConcrete) * n(prices.concrete?.[1]?.price || prices.concrete?.[0]?.price || '0');
                                                        const prelimCost = Math.ceil(n(prelim?.excavationVolume)) * n(prices.preliminary?.[0]?.price || '0') + Math.ceil(n(prelim?.backfillVolume)) * n(prices.preliminary?.[1]?.price || '0') + Math.ceil(n(prelim?.plinthArea)) * n(prices.preliminary?.[2]?.price || '0');

                                                          const totalBlocksCost = totalBlocks * n(fmat[0]?.price || '0');
                                                            const laborPrice = n(prices.labor?.[0]?.price || '0');
                                                              const slabConcreteForLabor = buildingArea * 0.3 * floors;
                                                                const laborTotal = n(struct?.footingConcrete) * laborPrice + n(struct?.neckConcrete) * laborPrice + n(struct?.columnConcrete) * floors * laborPrice + n(struct?.middConcrete) * laborPrice + slabConcreteForLabor * laborPrice;

                                                                  // تكلفة مواد التشطيبات
                                                                    const fmCost =
                                                                        totalBlocks * n(fmat[0]?.price || '0') +
                                                                            totalCement * n(fmat[2]?.price || '0') +
                                                                                totalSand * n(fmat[3]?.price || '0') +
                                                                                    totalAggregate * n(fmat[4]?.price || '0') +
                                                                                        totalMarbleArea * n(fmat[1]?.price || '0') +
                                                                                            Math.ceil(n(finishes?.paint?.putty) * floors) * n(fmat[5]?.price || '0') +
                                                                                                Math.ceil(n(finishes?.paint?.primer) * floors) * n(fmat[6]?.price || '0') +
                                                                                                    Math.ceil(n(finishes?.paint?.paint) * floors) * n(fmat[7]?.price || '0') +
                                                                                                        Math.ceil(n(finishes?.tile?.floor) * floors) * n(fmat[8]?.price || '0');

                                                                                                          // تكلفة عمالة التشطيبات
                                                                                                            const blockLaborCost = blockLaborMode === 'm2' ? blockLaborArea * blockLaborUnit : totalBlocks * blockLaborUnit;

                                                                                                              const flCost =
                                                                                                                  blockLaborCost +
                                                                                                                      totalMarbleLaborFloors * n(flab[1]?.price || '0') +
                                                                                                                          totalPlasterLaborFloors * n(flab[2]?.price || '0') +
                                                                                                                              totalPaintLaborFloors * n(flab[3]?.price || '0') +
                                                                                                                                  totalTileLaborFloors * n(flab[4]?.price || '0');

                                                                                                                                    const feCost =
                                                                                                                                        Math.ceil(n(finishes?.extras?.bathrooms) * floors) * n(fext[0]?.price || '0') +
                                                                                                                                            Math.ceil(n(finishes?.extras?.kitchens) * floors) * n(fext[1]?.price || '0') +
                                                                                                                                                totalWindows * n(doorsAndWindows[1]?.price || '0') +
                                                                                                                                                    totalDoors * n(doorsAndWindows[2]?.price || '0');

                                                                                                                                                      const grandTotal = cv(prelimCost + totalConcreteCost + totalSteelCost + totalBlocksCost + laborTotal + (fmCost + flCost + feCost));

                                                                                                                                                        const costPerM2 = (buildingArea > 0) ? grandTotal / buildingArea : 0;
                                                                                                                                                          const steelPerM2 = (buildingArea > 0) ? n(struct?.totalSteel) / buildingArea : 0;
                                                                                                                                                            const concretePerM2 = (buildingArea > 0) ? n(struct?.totalConcrete) / buildingArea : 0;

                                                                                                                                                              const steelPercent = grandTotal > 0 ? (cv(totalSteelCost) / grandTotal) * 100 : 0;
                                                                                                                                                                const concretePercent = grandTotal > 0 ? (cv(totalConcreteCost) / grandTotal) * 100 : 0;
                                                                                                                                                                  const laborPercent = grandTotal > 0 ? (cv(laborTotal) / grandTotal) * 100 : 0;
                                                                                                                                                                    const finishesPercent = grandTotal > 0 ? (cv((fmCost + flCost + feCost)) / grandTotal) * 100 : 0;

                                                                                                                                                                      return (
                                                                                                                                                                          <>
                                                                                                                                                                                {/* ملخص التشطيبات */}
                                                                                                                                                                                      <Card title={`ملخص التشطيبات (${cur})`} open={o.finishes} setOpen={() => setO((p: any) => ({ ...p, finishes: !p.finishes }))}>
                                                                                                                                                                                              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.7rem' }}>
                                                                                                                                                                                                        <thead><tr><th style={S.th}>البند</th><th style={S.th}>الكمية</th><th style={S.th}>سعر الوحدة</th><th style={S.th}>الإجمالي</th></tr></thead>
                                                                                                                                                                                                                  <tbody>
                                                                                                                                                                                                                              <tr><td style={S.td} colSpan={4}><strong>🧱 مواد التشطيبات</strong></td></tr>
                                                                                                                                                                                                                                          <Tr4 label={`البلوك (${floors} دور)`} qty={`${fm(totalBlocks)} بلوكة`} price={fm(cv(n(fmat[0]?.price || '0')))} total={fm(cv(totalBlocks * n(fmat[0]?.price || '0')))} />
                                                                                                                                                                                                                                                      <Tr4 label={`الأسمنت (${floors} دور)`} qty={`${fm(totalCement)} كيس`} price={fm(cv(n(fmat[2]?.price || '0')))} total={fm(cv(totalCement * n(fmat[2]?.price || '0')))} />
                                                                                                                                                                                                                                                                  <Tr4 label={`الرمل (${floors} دور)`} qty={`${fm(totalSand)} م³`} price={fm(cv(n(fmat[3]?.price || '0')))} total={fm(cv(totalSand * n(fmat[3]?.price || '0')))} />
                                                                                                                                                                                                                                                                              <Tr4 label={`الركام (${floors} دور)`} qty={`${fm(totalAggregate)} م³`} price={fm(cv(n(fmat[4]?.price || '0')))} total={fm(cv(totalAggregate * n(fmat[4]?.price || '0')))} />
                                                                                                                                                                                                                                                                                          <Tr4 label={`الرخام (${floors} دور)`} qty={`${fm(totalMarbleArea)} م²`} price={fm(cv(n(fmat[1]?.price || '0')))} total={fm(cv(totalMarbleArea * n(fmat[1]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                      <Tr4 label={`البلاط (${floors} دور)`} qty={`${fm(Math.ceil(n(finishes?.tile?.floor) * floors))} م²`} price={fm(cv(n(fmat[8]?.price || '0')))} total={fm(cv(Math.ceil(n(finishes?.tile?.floor) * floors) * n(fmat[8]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                  <Tr4 label={`المعجون (${floors} دور)`} qty={`${fm(Math.ceil(n(finishes?.paint?.putty) * floors))} كجم`} price={fm(cv(n(fmat[5]?.price || '0')))} total={fm(cv(Math.ceil(n(finishes?.paint?.putty) * floors) * n(fmat[5]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                              <Tr4 label={`الطلاء (${floors} دور)`} qty={`${fm(Math.ceil(n(finishes?.paint?.paint) * floors))} جالون`} price={fm(cv(n(fmat[7]?.price || '0')))} total={fm(cv(Math.ceil(n(finishes?.paint?.paint) * floors) * n(fmat[7]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                          <tr><td style={S.td} colSpan={4}><strong>👷 عمالة التشطيبات</strong></td></tr>
                                                                                                                                                                                                                                                                                                                                                      <Tr4 label={`بناء البلوك (${floors} دور)`} qty={blockLaborMode === 'm2' ? `${fm(blockLaborArea)} م²` : `${fm(totalBlocks)} بلوكة`} price={fm(cv(blockLaborUnit))} total={fm(cv(blockLaborCost))} />
                                                                                                                                                                                                                                                                                                                                                                  {hasMarble && (
                                                                                                                                                                                                                                                                                                                                                                                <Tr4 label={`تركيب الرخام (${floors} دور)`} qty={`${fm(totalMarbleLaborFloors)} م²`} price={fm(cv(n(flab[1]?.price || '0')))} total={fm(cv(totalMarbleLaborFloors * n(flab[1]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                        <Tr4 label={`التلييس (${floors} دور)`} qty={`${fmt(totalPlasterLaborFloors)} م²`} price={fm(cv(n(flab[2]?.price || '0')))} total={fm(cv(totalPlasterLaborFloors * n(flab[2]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                                                    <Tr4 label={`الطلاء (${floors} دور)`} qty={`${fmt(totalPaintLaborFloors)} م²`} price={fm(cv(n(flab[3]?.price || '0')))} total={fm(cv(totalPaintLaborFloors * n(flab[3]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                <Tr4 label={`البلاط (${floors} دور)`} qty={`${fmt(totalTileLaborFloors)} م²`} price={fm(cv(n(flab[4]?.price || '0')))} total={fm(cv(totalTileLaborFloors * n(flab[4]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={S.td} colSpan={4}><strong>🔧 تكاليف إضافية</strong></td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Tr4 label={`سباكة الحمامات (${floors} دور)`} qty={`${fm(Math.ceil(n(finishes?.extras?.bathrooms) * floors))} حمام`} price={fm(cv(n(fext[0]?.price || '0')))} total={fm(cv(Math.ceil(n(finishes?.extras?.bathrooms) * floors) * n(fext[0]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Tr4 label={`سباكة المطابخ (${floors} دور)`} qty={`${fm(Math.ceil(n(finishes?.extras?.kitchens) * floors))} مطبخ`} price={fm(cv(n(fext[1]?.price || '0')))} total={fm(cv(Math.ceil(n(finishes?.extras?.kitchens) * floors) * n(fext[1]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Tr4 label={`النوافذ (${floors} دور)`} qty={`${fm(totalWindows)} نافذة`} price={fm(cv(n(doorsAndWindows[1]?.price || '0')))} total={fm(cv(totalWindows * n(doorsAndWindows[1]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Tr4 label={`الأبواب (${floors} دور)`} qty={`${fm(totalDoors)} باب`} price={fm(cv(n(doorsAndWindows[2]?.price || '0')))} total={fm(cv(totalDoors * n(doorsAndWindows[2]?.price || '0')))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr style={S.total}><td style={S.td} colSpan={3}>إجمالي التشطيبات</td><td style={S.td}>{fm(cv((fmCost + flCost + feCost)))} {cur}</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* الملخص المالي النهائي */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Card title={`الملخص المالي النهائي (${cur})`} open={o.final} setOpen={() => setO((p: any) => ({ ...p, final: !p.final }))}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.7rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <thead><tr><th style={S.th}>البند</th><th style={S.th}>القيمة</th></tr></thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Tr label="الأعمال التمهيدية" value={`${fm(cv(prelimCost))} ${cur}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Tr label="الخرسانة" value={`${fm(cv(totalConcreteCost))} ${cur}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Tr label="الحديد" value={`${fm(cv(totalSteelCost))} ${cur}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Tr label={`البلوك الهوردي (${floors} دور)`} value={`${fm(cv(totalBlocksCost))} ${cur}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Tr label={`أجور المقاول (${floors} دور)`} value={`${fm(cv(laborTotal))} ${cur}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Tr label="إجمالي التشطيبات" value={`${fm(cv((fmCost + flCost + feCost)))} ${cur}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Tr label="إجمالي تكلفة المشروع" value={`${fm(grandTotal)} ${cur}`} total />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* مؤشرات هندسية */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Card title="مؤشرات هندسية" open={o.ind} setOpen={() => setO((p: any) => ({ ...p, ind: !p.ind }))}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ border: '1px solid #2196F3', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#f0f8ff' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>إجمالي الخرسانة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#2196F3', display: 'block' }}>{fmt(n(struct?.totalConcrete))} م³</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ border: '1px solid #FF9800', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#fff8f0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>إجمالي الحديد</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#FF9800', display: 'block' }}>{fmt(n(struct?.totalSteel))} طن</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ border: '1px solid #4CAF50', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#f0fff0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>تكلفة المتر المربع</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#4CAF50', display: 'block' }}>{fm(costPerM2)} {cur}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ border: '1px solid #f44336', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#fff0f0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>الحديد / م²</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#f44336', display: 'block' }}>{fmt(steelPerM2)} طن/م²</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ border: '1px solid #9C27B0', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#faf0ff' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>الخرسانة / م²</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#9C27B0', display: 'block' }}>{fmt(concretePerM2)} م³/م²</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* الخطوط التي تمثل النسب المئوية */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { label: 'نسبة تكلفة الحديد', val: steelPercent, color: '#f44336' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { label: 'نسبة تكلفة الخرسانة', val: concretePercent, color: '#2196F3' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { label: 'نسبة أجور المقاول', val: laborPercent, color: '#4CAF50' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { label: 'نسبة التشطيبات', val: finishesPercent, color: '#8B5CF6' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ].map((r, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={i} style={{ marginBottom: '6px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.65rem', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>{r.label}</span><span>{fmt(r.val)}%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ width: '100%', height: '6px', background: '#eee', borderRadius: '3px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ width: `${Math.min(r.val, 100)}%`, height: '100%', background: r.color, borderRadius: '3px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
      </Card>
          </>
            );
            };
