import { useState, useCallback, useRef } from 'react';
import type { Point, Wall, DrawingType, WallType } from '../core/types';
import { distance, snapAngle, getAngle } from '../core/geometry';
import { findSnapToFace } from '../core/snapToFace';
import { v4 as uuidv4 } from 'uuid';

const SNAP = 0.3;

interface DrawState {
  active: boolean;
    type: DrawingType;
      start: Point | null;
        end: Point | null;
        }

        export function useDrawing(walls: Wall[], onAdd: (w: Wall) => void) {
          const [d, setD] = useState<DrawState>({ active: false, type: null, start: null, end: null });
            const ref = useRef(d);
              ref.current = d;

                // ✅ إضافة حالة لتخزين معرف الجدار الأخير المرسوم
                  const [lastWallId, setLastWallId] = useState<string | null>(null);

                    const begin = useCallback((pt: Point, type: DrawingType) => {
                        if (!type) return;
                            const snap = findSnapToFace(pt, walls, undefined, SNAP);
                                setD({ active: true, type, start: snap?.point ?? pt, end: pt });
                                  }, [walls]);

                                    const move = useCallback((pt: Point) => {
                                        setD(prev => {
                                              if (!prev.active || !prev.start) return prev;
                                                    const angle = getAngle(prev.start, pt);
                                                          const snapped = snapAngle(angle);
                                                                let end: Point;
                                                                      if (snapped !== angle) {
                                                                              const dist = distance(prev.start, pt);
                                                                                      end = Math.abs(snapped) < 0.001 || Math.abs(snapped - Math.PI) < 0.001
                                                                                                ? { x: pt.x, y: prev.start.y }
                                                                                                          : { x: prev.start.x, y: pt.y };
                                                                                                                } else {
                                                                                                                        end = pt;
                                                                                                                              }
                                                                                                                                    const snap = findSnapToFace(end, walls, undefined, SNAP);
                                                                                                                                          return { ...prev, end: snap?.point ?? end };
                                                                                                                                              });
                                                                                                                                                }, [walls]);

                                                                                                                                                  const finishWithLength = useCallback((length: number) => {
                                                                                                                                                      const cur = ref.current;
                                                                                                                                                          if (!cur.active || !cur.start || !cur.end || !cur.type) return;
                                                                                                                                                              const angle = getAngle(cur.start, cur.end);
                                                                                                                                                                  const snapped = snapAngle(angle);
                                                                                                                                                                      let end: Point;
                                                                                                                                                                          if (snapped !== angle) {
                                                                                                                                                                                end = {
                                                                                                                                                                                        x: cur.start.x + Math.cos(snapped) * length,
                                                                                                                                                                                                y: cur.start.y + Math.sin(snapped) * length,
                                                                                                                                                                                                      };
                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                end = {
                                                                                                                                                                                                                        x: cur.start.x + Math.cos(angle) * length,
                                                                                                                                                                                                                                y: cur.start.y + Math.sin(angle) * length,
                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                              const newWall: Wall = {
                                                                                                                                                                                                                                                    id: uuidv4(),
                                                                                                                                                                                                                                                          start: { ...cur.start },
                                                                                                                                                                                                                                                                end,
                                                                                                                                                                                                                                                                      thickness: cur.type === 'exterior' ? 0.3 : 0.2,
                                                                                                                                                                                                                                                                            type: cur.type as WallType,
                                                                                                                                                                                                                                                                                  normalSign: 1,
                                                                                                                                                                                                                                                                                        lockDirection: false,
                                                                                                                                                                                                                                                                                              lockLength: false,
                                                                                                                                                                                                                                                                                                    lockMove: true,
                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                            onAdd(newWall);
                                                                                                                                                                                                                                                                                                                setLastWallId(newWall.id); // ✅ حفظ معرف الجدار الأخير
                                                                                                                                                                                                                                                                                                                    reset();
                                                                                                                                                                                                                                                                                                                      }, [onAdd]);

                                                                                                                                                                                                                                                                                                                        const finish = useCallback(() => {
                                                                                                                                                                                                                                                                                                                            const cur = ref.current;
                                                                                                                                                                                                                                                                                                                                if (!cur.active || !cur.start || !cur.end || !cur.type) { reset(); return; }
                                                                                                                                                                                                                                                                                                                                    if (distance(cur.start, cur.end) < 0.1) { reset(); return; }
                                                                                                                                                                                                                                                                                                                                        const newWall: Wall = {
                                                                                                                                                                                                                                                                                                                                              id: uuidv4(),
                                                                                                                                                                                                                                                                                                                                                    start: { ...cur.start },
                                                                                                                                                                                                                                                                                                                                                          end: { ...cur.end },
                                                                                                                                                                                                                                                                                                                                                                thickness: cur.type === 'exterior' ? 0.3 : 0.2,
                                                                                                                                                                                                                                                                                                                                                                      type: cur.type as WallType,
                                                                                                                                                                                                                                                                                                                                                                            normalSign: 1,
                                                                                                                                                                                                                                                                                                                                                                                  lockDirection: false,
                                                                                                                                                                                                                                                                                                                                                                                        lockLength: false,
                                                                                                                                                                                                                                                                                                                                                                                              lockMove: true,
                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                      onAdd(newWall);
                                                                                                                                                                                                                                                                                                                                                                                                          setLastWallId(newWall.id); // ✅ حفظ معرف الجدار الأخير
                                                                                                                                                                                                                                                                                                                                                                                                              reset();
                                                                                                                                                                                                                                                                                                                                                                                                                }, [onAdd]);

                                                                                                                                                                                                                                                                                                                                                                                                                  const reset = useCallback(() => setD({ active: false, type: null, start: null, end: null }), []);

                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                        isDrawing: d.active,
                                                                                                                                                                                                                                                                                                                                                                                                                            drawingType: d.type,
                                                                                                                                                                                                                                                                                                                                                                                                                                tempStart: d.start,
                                                                                                                                                                                                                                                                                                                                                                                                                                    tempEnd: d.end,
                                                                                                                                                                                                                                                                                                                                                                                                                                        lastWallId, // ✅ إرجاع معرف الجدار الأخير
                                                                                                                                                                                                                                                                                                                                                                                                                                            begin,
                                                                                                                                                                                                                                                                                                                                                                                                                                                move,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    finish,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        finishWithLength,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            cancel: reset,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }