import React from 'react';
import type { Column, Window, Door, Wall } from '../../core/types';

interface Props {
  selected: { id: string; type: 'column' | 'window' | 'door' } | null;
    columns: Column[];
      windows: Window[];
        doors: Door[];
          walls: Wall[];
            updateColumn: (id: string, patch: Partial<Column>) => void;
              updateWindow: (id: string, patch: Partial<Window>) => void;
                updateDoor: (id: string, patch: Partial<Door>) => void;
                }

                const inputStyle: React.CSSProperties = {
                  width: '70px',
                    padding: '6px 8px',
                      borderRadius: 6,
                        border: '1px solid #ccc',
                          fontSize: 14,
                            textAlign: 'center',
                            };

                            const labelStyle: React.CSSProperties = {
                              fontWeight: 700,
                                fontSize: 13,
                                  color: '#003366',
                                  };

                                  const buttonStyle: React.CSSProperties = {
                                    padding: '6px 12px',
                                      borderRadius: 6,
                                        border: 'none',
                                          color: '#fff',
                                            cursor: 'pointer',
                                              fontWeight: 700,
                                                fontSize: 13,
                                                };

                                                export const ElementProperties: React.FC<Props> = ({ selected, columns, windows, doors, walls, updateColumn, updateWindow, updateDoor }) => {
                                                  if (!selected) return null;

                                                    const handleFocus = (e: React.FocusEvent<HTMLInputElement>) => e.target.select();
                                                      const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
                                                          if (e.key === 'Enter') (e.target as HTMLInputElement).blur();
                                                            };

                                                              if (selected.type === 'column') {
                                                                  const col = columns.find(c => c.id === selected.id);
                                                                      if (!col) return null;
                                                                          return (
                                                                                <div style={{ display: 'flex', gap: '12px', alignItems: 'center', padding: '8px 12px', background: '#f8f8f8', borderRadius: 8, margin: 8, flexWrap: 'wrap' }}>
                                                                                        <span style={{ fontWeight: 700, color: '#003366' }}>📌</span>
                                                                                                <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                          <span style={labelStyle}>العرض (م):</span>
                                                                                                                    <input type="number" step="0.01" value={col.width} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateColumn(col.id, { width: Number(e.target.value) })} />
                                                                                                                            </div>
                                                                                                                                    <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                              <span style={labelStyle}>الطول (م):</span>
                                                                                                                                                        <input type="number" step="0.01" value={col.length} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateColumn(col.id, { length: Number(e.target.value) })} />
                                                                                                                                                                </div>
                                                                                                                                                                        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                                                                  <span style={labelStyle}>الدوران (°):</span>
                                                                                                                                                                                            <input type="number" step="1" value={((col.rotation || 0) * 180) / Math.PI} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateColumn(col.id, { rotation: (Number(e.target.value) * Math.PI) / 180 })} />
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                              );
                                                                                                                                                                                                                }

                                                                                                                                                                                                                  if (selected.type === 'window') {
                                                                                                                                                                                                                      const win = windows.find(w => w.id === selected.id);
                                                                                                                                                                                                                          if (!win) return null;
                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                    <div style={{ display: 'flex', gap: '12px', alignItems: 'center', padding: '8px 12px', background: '#f8f8f8', borderRadius: 8, margin: 8, flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                            <span style={{ fontWeight: 700, color: '#003366' }}>🪟</span>
                                                                                                                                                                                                                                                    <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                                                                                                                                              <span style={labelStyle}>العرض (م):</span>
                                                                                                                                                                                                                                                                        <input type="number" step="0.01" value={win.width} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateWindow(win.id, { width: Number(e.target.value) })} />
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                                                                                                                                                                                  <span style={labelStyle}>الارتفاع (م):</span>
                                                                                                                                                                                                                                                                                                            <input type="number" step="0.01" value={win.height} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateWindow(win.id, { height: Number(e.target.value) })} />
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                                                                                                                                                                                                                      <span style={labelStyle}>السماكة (م):</span>
                                                                                                                                                                                                                                                                                                                                                <input type="number" step="0.01" value={win.thickness} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateWindow(win.id, { thickness: Number(e.target.value) })} />
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                      if (selected.type === 'door') {
                                                                                                                                                                                                                                                                                                                                                                          const door = doors.find(d => d.id === selected.id);
                                                                                                                                                                                                                                                                                                                                                                              if (!door) return null;
                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', gap: '12px', alignItems: 'center', padding: '8px 12px', background: '#f8f8f8', borderRadius: 8, margin: 8, flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                <span style={{ fontWeight: 700, color: '#003366' }}>🚪</span>
                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={labelStyle}>العرض (م):</span>
                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="number" step="0.01" value={door.width} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateDoor(door.id, { width: Number(e.target.value) })} />
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={labelStyle}>الارتفاع (م):</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="number" step="0.01" value={door.height} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateDoor(door.id, { height: Number(e.target.value) })} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={labelStyle}>السماكة (م):</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="number" step="0.01" value={door.thickness} style={inputStyle} onFocus={handleFocus} onKeyDown={handleKeyDown} onChange={e => updateDoor(door.id, { thickness: Number(e.target.value) })} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => updateDoor(door.id, { swing: door.swing === 1 ? -1 : 1 })} style={{ ...buttonStyle, background: '#06f' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🔄 انعكاس
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* ✅ تم حذف زر الانقلاب */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };