import React from 'react';
import type { Wall, Point, CanvasView } from '../../core/types';
import { worldToScreen, distance, wallRectangle } from '../../core/geometry';

interface Props {
  walls: Wall[];
    view: CanvasView;
      width: number;
        height: number;
          selectedId: string | null;
            tempStart: Point | null;
              tempEnd: Point | null;
              scale?: number;
              }

              const COLORS = {
                // توحيد لون الجدران
                  exterior: '#333',
                    interior: '#333',
                      selected: '#0a0',
                        handle: '#06f',
                          preview: '#06f',
                            dimension: '#888',
                              grid: '#e0e0e0',
                                gridBorder: '#aaa',
                                };

                                const GRID_EXTENT = 20;
                                const GRID_SPACING = 0.5;

                                export const CanvasRenderer: React.FC<Props> = React.memo(({
                                  walls,
                                    view,
                                      width,
                                        height,
                                          selectedId,
                                            tempStart,
                                              tempEnd,
                                              scale = 1,
                                              }) => {
                                                const [showGrid, setShowGrid] = React.useState(true);

                                                  React.useEffect(() => {
                                                      const handler = (e: Event) => {
                                                            setShowGrid((e as CustomEvent<boolean>).detail !== false);
                                                                };

                                                                    window.addEventListener('pdf-export-grid', handler);
                                                                        return () => window.removeEventListener('pdf-export-grid', handler);
                                                                          }, []);

                                                                            const toScreen = (p: Point): Point =>
                                                                                worldToScreen(
                                                                                      p.x,
                                                                                            p.y,
                                                                                                  width,
                                                                                                        height,
                                                                                                              view.zoom,
                                                                                                                    view.offsetX,
                                                                                                                          view.offsetY
                                                                                                                              );

                                                                                                                                const drawGrid = (ctx: CanvasRenderingContext2D) => {
                                                                                                                                    const topLeft = toScreen({ x: -GRID_EXTENT, y: -GRID_EXTENT });
                                                                                                                                        const bottomRight = toScreen({ x: GRID_EXTENT, y: GRID_EXTENT });

                                                                                                                                            ctx.strokeStyle = COLORS.gridBorder;
                                                                                                                                                ctx.lineWidth = 2 * scale;
                                                                                                                                                    ctx.strokeRect(
                                                                                                                                                          topLeft.x,
                                                                                                                                                                topLeft.y,
                                                                                                                                                                      bottomRight.x - topLeft.x,
                                                                                                                                                                            bottomRight.y - topLeft.y
                                                                                                                                                                                );

                                                                                                                                                                                    ctx.strokeStyle = COLORS.grid;
                                                                                                                                                                                  ctx.lineWidth = 0.5 * scale;

                                                                                                                                                                                            for (let x = -GRID_EXTENT; x <= GRID_EXTENT; x += GRID_SPACING) {
                                                                                                                                                                                                  const sx = toScreen({ x, y: 0 }).x;
                                                                                                                                                                                                        ctx.beginPath();
                                                                                                                                                                                                              ctx.moveTo(sx, toScreen({ x, y: -GRID_EXTENT }).y);
                                                                                                                                                                                                                    ctx.lineTo(sx, toScreen({ x, y: GRID_EXTENT }).y);
                                                                                                                                                                                                                          ctx.stroke();
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                  for (let y = -GRID_EXTENT; y <= GRID_EXTENT; y += GRID_SPACING) {
                                                                                                                                                                                                                                        const sy = toScreen({ x: 0, y }).y;
                                                                                                                                                                                                                                              ctx.beginPath();
                                                                                                                                                                                                                                                    ctx.moveTo(toScreen({ x: -GRID_EXTENT, y }).x, sy);
                                                                                                                                                                                                                                                          ctx.lineTo(toScreen({ x: GRID_EXTENT, y }).x, sy);
                                                                                                                                                                                                                                                                ctx.stroke();
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                        // ✅ دالة جديدة لرسم الجدران ككتل مملوءة
                                                                                                                                                                                                                                                                          const drawWall = (
                                                                                                                                                                                                                                                                              ctx: CanvasRenderingContext2D,
                                                                                                                                                                                                                                                                                  wall: Wall,
                                                                                                                                                                                                                                                                                      selected: boolean
                                                                                                                                                                                                                                                                                        ) => {
                                                                                                                                                                                                                                                                                            const rect = wallRectangle(wall);
                                                                                                                                                                                                                                                                                                // استخراج الزوايا الأربعة للجدار
                                                                                                                                                                                                                                                                                                    const corners = rect.corners.map(toScreen);

                                                                                                                                                                                                                                                                                                        // رسم كتلة مملوءة
                                                                                                                                                                                                                                                                                                            ctx.fillStyle = selected ? COLORS.selected : COLORS.exterior;
                                                                                                                                                                                                                                                                                                                ctx.beginPath();
                                                                                                                                                                                                                                                                                                                    ctx.moveTo(corners[0].x, corners[0].y);
                                                                                                                                                                                                                                                                                                                        ctx.lineTo(corners[1].x, corners[1].y);
                                                                                                                                                                                                                                                                                                                            ctx.lineTo(corners[2].x, corners[2].y);
                                                                                                                                                                                                                                                                                                                                ctx.lineTo(corners[3].x, corners[3].y);
                                                                                                                                                                                                                                                                                                                                    ctx.closePath();
                                                                                                                                                                                                                                                                                                                                        ctx.fill();

                                                                                                                                                                                                                                                                                                                                            if (selected) {
                                                                                                                                                                                                                                                                                                                                                  const s = toScreen(wall.start);
                                                                                                                                                                                                                                                                                                                                                        const e = toScreen(wall.end);

                                                                                                                                                                                                                                                                                                                                                              ctx.fillStyle = COLORS.handle;
                                                                                                                                                                                                                                                                                                                                                                    [s, e].forEach(p => ctx.fillRect(p.x - 4, p.y - 4, 8, 8));

                                                                                                                                                                                                                                                                                                                                                                          const mid = toScreen({
                                                                                                                                                                                                                                                                                                                                                                                  x: (wall.start.x + wall.end.x) / 2,
                                                                                                                                                                                                                                                                                                                                                                                          y: (wall.start.y + wall.end.y) / 2,
                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                      ctx.fillStyle = COLORS.dimension;
                                                                                                                                                                                                                                                                                                                                                                                                            ctx.font = `${Math.max(11, 12 * view.zoom * scale)}px sans-serif`;
                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.textAlign = 'center';
                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fillText(distance(wall.start, wall.end).toFixed(2), mid.x + 15, mid.y - 15);
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                React.useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                    const canvas = canvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!canvas) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                            const ctx = canvas.getContext('2d');
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!ctx) return;

                                                                                                          
                                                                                                            // ✅ ضبط أبعاد الـ Canvas حسب scale
                                                                                                              canvas.width = width * scale;
                                                                                                                canvas.height = height * scale;
                                                                                                                  ctx.scale(scale, scale); // ✅ تكبير الرسم
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.clearRect(0, 0, width, height);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fillStyle = '#fafafa';
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.fillRect(0, 0, width, height);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (showGrid) drawGrid(ctx);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    walls.forEach(w => drawWall(ctx, w, w.id === selectedId));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (tempStart && tempEnd) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const s = toScreen(tempStart);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const e = toScreen(tempEnd);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.strokeStyle = COLORS.preview;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.lineWidth = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.setLineDash([6, 4]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.moveTo(s.x, s.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.lineTo(e.x, e.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.stroke();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ctx.setLineDash([]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const mid = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  x: (s.x + e.x) / 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          y: (s.y + e.y) / 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.fillStyle = COLORS.preview;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.font = `${Math.max(12, 14 * view.zoom * scale)}px sans-serif`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.textAlign = 'center';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fillText(distance(tempStart, tempEnd).toFixed(2), mid.x + 15, mid.y - 15);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  walls,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      view,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  selectedId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tempStart,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tempEnd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              showGrid,
                                                                                                                     scale,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const canvasRef = React.useRef<HTMLCanvasElement>(null);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ref={canvasRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width={width}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height={height}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ display: 'block' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });