import React from 'react';
import type { Column, Window, Door, Wall, CanvasView } from '../../core/types';
import { worldToScreen, PX_PER_METER, getAngle, distance } from '../../core/geometry';

interface Props {
  columns: Column[];
    windows: Window[];
      doors: Door[];
        walls: Wall[];
          view: CanvasView;
            width: number;
              height: number;
                scale?: number; // ✅ إضافة scale للدقة العالية عند التصدير
                }

                export const ElementLayer: React.FC<Props> = React.memo(({ columns, windows, doors, walls, view, width, height, scale = 1 }) => {
                  const canvasRef = React.useRef<HTMLCanvasElement>(null);

                    React.useEffect(() => {
                        const canvas = canvasRef.current;
                            if (!canvas) return;
                                const ctx = canvas.getContext('2d');
                                    if (!ctx) return;

                                        // ✅ ضبط أبعاد الـ Canvas حسب scale (للتصدير عالي الدقة)
                                            canvas.width = width * scale;
                                                canvas.height = height * scale;
                                                    ctx.scale(scale, scale); // تكبير الرسم بالكامل

                                                        ctx.clearRect(0, 0, width, height);

                                                            // رسم الأعمدة
                                                                columns.forEach(col => {
                                                                      const pos = worldToScreen(col.position.x, col.position.y, width, height, view.zoom, view.offsetX, view.offsetY);
                                                                            const w = col.width * PX_PER_METER * view.zoom;
                                                                                  const l = col.length * PX_PER_METER * view.zoom;

                                                                                        ctx.save();
                                                                                              ctx.translate(pos.x, pos.y);
                                                                                                    ctx.rotate(col.rotation || 0);
                                                                                                          ctx.fillStyle = '#999';
                                                                                                                ctx.fillRect(-w / 2, -l / 2, w, l);
                                                                                                                      ctx.restore();
                                                                                                                          });

                                                                                                                              // رسم النوافذ
                                                                                                                                  windows.forEach(win => {
                                                                                                                                        const wall = walls.find(w => w.id === win.wallId);
                                                                                                                                              if (!wall) return;

                                                                                                                                                    const wallAngle = getAngle(wall.start, wall.end);
                                                                                                                                                          const normal = { x: -Math.sin(wallAngle), y: Math.cos(wallAngle) };
                                                                                                                                                                const halfThick = win.thickness / 2;

                                                                                                                                                                      const center = win.center ?? (() => {
                                                                                                                                                                              const len = distance(wall.start, wall.end);
                                                                                                                                                                                      return {
                                                                                                                                                                                                x: wall.start.x + ((win.position + win.width / 2) / len) * (wall.end.x - wall.start.x),
                                                                                                                                                                                                          y: wall.start.y + ((win.position + win.width / 2) / len) * (wall.end.y - wall.start.y),
                                                                                                                                                                                                                  };
                                                                                                                                                                                                                        })();

                                                                                                                                                                                                                              const startX = center.x - Math.cos(wallAngle) * win.width / 2;
                                                                                                                                                                                                                                    const startY = center.y - Math.sin(wallAngle) * win.width / 2;
                                                                                                                                                                                                                                          const endX = center.x + Math.cos(wallAngle) * win.width / 2;
                                                                                                                                                                                                                                                const endY = center.y + Math.sin(wallAngle) * win.width / 2;

                                                                                                                                                                                                                                                      const corners = [
                                                                                                                                                                                                                                                              { x: startX + normal.x * halfThick, y: startY + normal.y * halfThick },
                                                                                                                                                                                                                                                                      { x: endX + normal.x * halfThick, y: endY + normal.y * halfThick },
                                                                                                                                                                                                                                                                              { x: endX - normal.x * halfThick, y: endY - normal.y * halfThick },
                                                                                                                                                                                                                                                                                      { x: startX - normal.x * halfThick, y: startY - normal.y * halfThick },
                                                                                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                                                                                  const screenCorners = corners.map(c =>
                                                                                                                                                                                                                                                                                                          worldToScreen(c.x, c.y, width, height, view.zoom, view.offsetX, view.offsetY)
                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                      // ✅ مسح منطقة الجدار باللون الأبيض قبل رسم النافذة
                                                                                                                                                                                                                                                                                                                            ctx.fillStyle = '#ffffff';
                                                                                                                                                                                                                                                                                                                                  ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                        ctx.moveTo(screenCorners[0].x, screenCorners[0].y);
                                                                                                                                                                                                                                                                                                                                              ctx.lineTo(screenCorners[1].x, screenCorners[1].y);
                                                                                                                                                                                                                                                                                                                                                    ctx.lineTo(screenCorners[2].x, screenCorners[2].y);
                                                                                                                                                                                                                                                                                                                                                          ctx.lineTo(screenCorners[3].x, screenCorners[3].y);
                                                                                                                                                                                                                                                                                                                                                                ctx.closePath();
                                                                                                                                                                                                                                                                                                                                                                      ctx.fill();

                                                                                                                                                                                                                                                                                                                                                                            // إطار النافذة (أزرق)
                                                                                                                                                                                                                                                                                                                                                                                  ctx.strokeStyle = '#06f';
ctx.lineWidth = Math.max(0.8, 2 * view.zoom * scale); // ✅ حد أدنى 0.8 بكسل
                                                                                                                                                                                                                                                                                                                                                                                              ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                    ctx.moveTo(screenCorners[0].x, screenCorners[0].y);
                                                                                                                                                                                                                                                                                                                                                                                                          ctx.lineTo(screenCorners[1].x, screenCorners[1].y);
                                                                                                                                                                                                                                                                                                                                                                                                                ctx.lineTo(screenCorners[2].x, screenCorners[2].y);
                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.lineTo(screenCorners[3].x, screenCorners[3].y);
                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.closePath();
                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.stroke();

                                                                                                                                                                                                                                                                                                                                                                                                                                        const gap = 0.05;
                                                                                                                                                                                                                                                                                                                                                                                                                                              const line1Start = worldToScreen(startX + normal.x * gap, startY + normal.y * gap, width, height, view.zoom, view.offsetX, view.offsetY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const line1End = worldToScreen(endX + normal.x * gap, endY + normal.y * gap, width, height, view.zoom, view.offsetX, view.offsetY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const line2Start = worldToScreen(startX - normal.x * gap, startY - normal.y * gap, width, height, view.zoom, view.offsetX, view.offsetY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const line2End = worldToScreen(endX - normal.x * gap, endY - normal.y * gap, width, height, view.zoom, view.offsetX, view.offsetY);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.strokeStyle = '#FFD700';
ctx.lineWidth = Math.max(0.8, 1.5 * view.zoom * scale); // ✅ حد أدنى 0.8 بكسل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.moveTo(line1Start.x, line1Start.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.lineTo(line1End.x, line1End.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ctx.stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.moveTo(line2Start.x, line2Start.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.lineTo(line2End.x, line2End.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // رسم الأبواب
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        doors.forEach(door => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const wall = walls.find(w => w.id === door.wallId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!wall) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const len = distance(wall.start, wall.end);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (len === 0) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const wallAngle = getAngle(wall.start, wall.end);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const normal = { x: -Math.sin(wallAngle), y: Math.cos(wallAngle) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const halfThick = wall.thickness / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const rotation = door.rotation || 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const center = door.center ?? (() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x: wall.start.x + ((door.position + door.width / 2) / len) * (wall.end.x - wall.start.x),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          y: wall.start.y + ((door.position + door.width / 2) / len) * (wall.end.y - wall.start.y),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const centerScreen = worldToScreen(center.x, center.y, width, height, view.zoom, view.offsetX, view.offsetY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const doorWidthPx = door.width * PX_PER_METER * view.zoom;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const wallThicknessPx = wall.thickness * PX_PER_METER * view.zoom;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.save();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.translate(centerScreen.x, centerScreen.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.rotate(rotation);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // مسح منطقة الجدار باللون الأبيض
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fillStyle = '#ffffff';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.fillRect(-doorWidthPx / 2, -wallThicknessPx / 2, doorWidthPx, wallThicknessPx);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // رسم ورقة الباب والقوس والمفصلة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const hingeLocalX = door.hinge === 'start' ? -doorWidthPx / 2 : doorWidthPx / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const hingeScreen = { x: hingeLocalX, y: 0 };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const swingSign = door.swing || 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const leafEndScreen = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    x: hingeScreen.x,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            y: hingeScreen.y + swingSign * doorWidthPx,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.strokeStyle = '#f00';
ctx.lineWidth = Math.max(1, 3 * view.zoom * scale); // ✅ حد أدنى 1 بكسل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.moveTo(hingeScreen.x, hingeScreen.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.lineTo(leafEndScreen.x, leafEndScreen.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.stroke();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const arcRadius = doorWidthPx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const startAngle = swingSign > 0 ? 0 : -Math.PI / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const endAngle = swingSign > 0 ? Math.PI / 2 : 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.strokeStyle = '#f00';
ctx.lineWidth = Math.max(0.8, 1.5 * view.zoom * scale); // ✅ حد أدنى 0.8 بكسل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.arc(hingeScreen.x, hingeScreen.y, arcRadius, startAngle, endAngle);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.stroke();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.fillStyle = '#f00';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.beginPath();
ctx.arc(hingeScreen.x, hingeScreen.y, Math.max(1, 4 * view.zoom * scale), 0, Math.PI * 2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.fill();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ctx.restore();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }, [columns, windows, doors, walls, view, width, height, scale]); // ✅ إضافة scale للتبعية

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ref={canvasRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width={width * scale} // ✅ إضافة scale لأبعاد الـ canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  height={height * scale} // ✅ إضافة scale لأبعاد الـ canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ position: 'absolute', top: 0, left: 0, pointerEvents: 'none', display: 'block' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });